### PR TITLE
[Proposal] Persistent Storage

### PR DESCRIPTION
**Pull request by markturansky**

### CODE REVIEW

**Comment by markturansky** [comment]
@smarterclayton

Rewritten with a single new 1st order object (PersistentStorage) and the request for persistence coming from within the pod.

**Comment by markturansky** [comment]
@jwhonce

**Comment by smarterclayton** [comment]
How do I list the volume that has the data that my postgresql pod wrote to it before the pod got deleted?

**Comment by markturansky** [comment]
@smarterclayton That's the "Discovery" section, that currently only shows a mock of what storage is available.  Hidden amongst the text, "An API and CLI is needed to view available and in-use storage by namespace."

I need to call out more attention to the interface required by the PersistantStorageController, but one would be implemented for each type of VolumeSource being made available.  Cloud controllers would easily support creation of new storage for the pool.  The NFS controller would require more elaborate solutions for creation, but allowing NFS mounts is supported OOTB.

**Pull request closed without merging**
